### ISSUE TITLE
Custom resurvey interval

### ISSUE THREAD

**Issue by Dimitar5555** [Zverik/every_door#933]
Currently the app has a hardcoded resurvey interval of 60 days for shops and amenities. It would be nice if there was an option to change it to something else (like 90 or 120 days). Every city is quite unique and tenant turnover rates aren't the same.

**Comment by Zverik** [comment]
It is not exactly hardcoded, and you can change it with a simple plugin. [See here](https://every-door.app/plugins/metadata/modes/#amenity) for an explanation. It would be something like:

```yaml
id: three_months
name: Extend validation interval to 90 days

modes:
  amenity:
    checkIntervals:
      structure: 360
      amenity: 90
```
